import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import { Root } from '@/components/Root/Root';
import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js 14 Telegram Mini Apps Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren<unknown>>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Root>{children}</Root>
      </body>
    </html>
  );
}
