import type { Metadata } from 'next';
import { Providers } from '@/app/providers';

import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js 14 Telegram Mini Apps Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
